name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: curl, json, pcntl
        ini-values: phar.readonly=0
    - uses: php-actions/composer@v6
      with:
        php_version: 8.1
    - uses: php-actions/phpunit@v3
      with:
        php_version: 8.1
    - name: Build phar
      run: ./vendor/bin/drutiny-packager $GITHUB_REF_NAME
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: acquia-drutiny*.phar
